name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1.3
      with:
       version: latest
       platform: x64
    - name: Build and run program
      run: cd gen_biome_img; gcc gen_biome_img.c ../libcubiomes.a -lm -fwrapv -O3 -o ./gen_biome_img.out; cd -; cd gen_biome_img; ./gen_biome_img.out; cd -